import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="flex justify-center font-[family-name:var(--font-geist-sans)] p-4 sm:p-8 h-dvh">
          <main className="flex grow lg:max-w-2/3 md:max-w-4/5 shadow-sm p-4 sm:p-8 bg-(--background) rounded-lg relative">
            <section
              aria-labelledby="todo-heading"
              className="flex flex-col w-full"
            >
              <h1
                id="todo-heading"
                className="text-4xl font-bold text-blue-600 sm:mb-4 text-center p-4 pt-0 sm:p-6 "
              >
                TODO&apos;s List
              </h1>

              {children}
            </section>
          </main>
        </div>
      </body>
    </html>
  );
}
